name: Update GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: 
    branches: ["master", "main"]
    paths:
      - .github/workflows/metrics.yaml
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: prod
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: gabrielfu
          template: classic
          base: ""
          filename: github_metrics.svg

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_sections: most-used, recently-used
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: css, jupyter notebook, html
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 1000
          plugin_languages_threshold: 0%
          plugin_languages_indepth: yes
          commits_authoring: Gabriel Fu, gabrielfu, gabrielfu@users.noreply.github.com
          plugin_languages_details: lines, percentage
          plugin_languages_other: no
